name: Continuous Integration Workflow

on: [push]

jobs:
  go-postgres:
    name: Go Postgres
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Cache Go vendor packages
        uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Download Go vendor packages
        run: go mod download
      - name: Set up Yarn for Contracts
        run: yarn setup:contracts
      - name: Run tests
        run: go test -v -p 3 -parallel 2 ./...
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable

  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: smartcontract/builder:1.0.31
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Sanity check $PATH
        run: echo $PATH
      - name: Check Rust toolchain
        run: rustup toolchain list
      - name: Run Rust test
        run: ./tools/ci/rust_test

  geth-postgres:
    name: Geth Postgres
    runs-on: self-hosted
    env:
      GETH_MODE: true
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run tests
        run: cd ./tools/docker && timeout --foreground 1200s ./compose test

  parity-postgres:
    name: Parity Postgres
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run tests
        run: cd ./tools/docker && timeout --foreground 1200s ./compose test

  solidity:
    name: Solidity
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Install python packages
        run: pip3 install -r requirements.txt
      - name: Run tests
        run: ./tools/ci/solidity_test
      - name: Upload test artifact
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./integration/logs

  styleguide:
    name: Run styleguide tests
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run styleguide tests
        run: yarn workspace @chainlink/styleguide run test

  json-api-client:
    name: JSON API client
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run JSON API client tests
        run: yarn workspace @chainlink/json-api-client run test

  operator-ui:
    name: Operator UI
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Init GCloud
        run: ./tools/ci/init_gcloud
      - name: Run Operator UI tests
        run: ./tools/ci/operator_ui_test
      - name: Upload test artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./integration/logs

  explorer:
    name: Explorer
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    env:
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run Yarn migrations
        run: yarn workspace @chainlink/explorer run test:migration:run
      - name: Run Server Tests
        run: yarn workspace @chainlink/explorer run test:ci
      - name: Run Client dependency setup
        run: yarn workspace @chainlink/explorer-client run setup
      - name: Run Client tests
        run: yarn workspace @chainlink/explorer-client run test:ci
      - name: Upload test artifacts
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: ./integration/logs

  feeds:
    name: Feeds
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run Feeds setup
        run: yarn workspace @chainlink/feeds setup
      - name: Run Feeds tests
        run: yarn workspace @chainlink/feeds run test
        env:
          CI: true

  reportcoverage:
    name: Report test coverage
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    needs: [go-postgres, solidity, operator-ui, rust, explorer]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Init GCloud
        run: ./tools/ci/init_gcloud
      - name: Run coverage report
        run: ./tools/ci/report_coverage

  check_if_rebase_needed:
    name: Check if rebase needed
    runs-on: ubuntu-latest
    container: alpine/git
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check if rebase is needed
        run: tools/bin/check_if_rebase_needed

  lint:
    name: Run Yarn lint
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run Yarn lint
        run: yarn lint

  prepublish_npm:
    name: Prepublish NPM
    runs-on: ubuntu-latest
    container: smartcontract/builder:1.0.29
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Save CACHE_VERSION for future hashing
        env:
          CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: echo $CACHE_VERSION > cache.version
      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        with:
          path: /usr/local/share/.cache/yarn
          key: v${{ hashFiles('cache.version') }}--yarn--vendor--${{ hashFiles('yarn.lock') }}
      - name: Install Yarn dependencies
        run: make yarndep
      - name: Run prepublish NPM test
        run: ./tools/ci/prepublish_npm_test

